export const USER_ROLES = {
  STUDENT: 'STUDENT',
  DRIVER: 'DRIVER',
  ADMIN: 'ADMIN',
} as const;

export const USER_STATUSES = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  DEACTIVATED: 'DEACTIVATED',
} as const;

export const VERIFICATION_STATUSES = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
} as const;

export const DRIVER_STATUSES = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
  ON_LEAVE: 'ON_LEAVE',
} as const;

export const VEHICLE_TYPES = {
  CAB_4: 'CAB_4',
  CAB_6: 'CAB_6',
  SHUTTLE_12: 'SHUTTLE_12',
  BUS_24: 'BUS_24',
} as const;

export const VEHICLE_STATUSES = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  MAINTENANCE: 'MAINTENANCE',
} as const;

export const PLAN_TIERS = {
  BASIC: 'BASIC',
  STANDARD: 'STANDARD',
  PREMIUM: 'PREMIUM',
} as const;

export const SUBSCRIPTION_STATUSES = {
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
} as const;

export const TRIP_TYPES = {
  MORNING_PICKUP: 'MORNING_PICKUP',
  EVENING_DROP: 'EVENING_DROP',
} as const;

export const TRIP_STATUSES = {
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export const BOOKING_STATUSES = {
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
  NO_SHOW: 'NO_SHOW',
} as const;

export const PASSENGER_STATUSES = {
  WAITING: 'WAITING',
  BOARDED: 'BOARDED',
  NO_SHOW: 'NO_SHOW',
} as const;

export const PASS_STATUSES = {
  ACTIVE: 'ACTIVE',
  USED: 'USED',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
} as const;

export const PAYMENT_METHODS = {
  UPI: 'UPI',
  DEBIT_CARD: 'DEBIT_CARD',
  CREDIT_CARD: 'CREDIT_CARD',
  NET_BANKING: 'NET_BANKING',
  WALLET: 'WALLET',
} as const;

export const PAYMENT_STATUSES = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
} as const;

export const COMPLAINT_CATEGORIES = {
  BOOKING: 'BOOKING',
  PAYMENT: 'PAYMENT',
  DRIVER: 'DRIVER',
  VEHICLE: 'VEHICLE',
  PASS_QR: 'PASS_QR',
  SUBSCRIPTION: 'SUBSCRIPTION',
  LOST_ITEM: 'LOST_ITEM',
  OTHER: 'OTHER',
} as const;

export const COMPLAINT_PRIORITIES = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
} as const;

export const COMPLAINT_STATUSES = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
} as const;

export const NOTIFICATION_PRIORITIES = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
} as const;

export const NOTIFICATION_TYPES = {
  // Booking events
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_CONFIRMED: 'BOOKING_CONFIRMED',
  BOOKING_ACCEPTED: 'BOOKING_ACCEPTED',
  BOOKING_REJECTED: 'BOOKING_REJECTED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  NEW_RIDE_REQUEST: 'NEW_RIDE_REQUEST',

  // Dispatch & Vehicle Assignment
  DRIVER_ASSIGNED: 'DRIVER_ASSIGNED',
  VEHICLE_ASSIGNED: 'VEHICLE_ASSIGNED',

  // Trip Lifecycle
  TRIP_STARTED: 'TRIP_STARTED',
  TRIP_COMPLETED: 'TRIP_COMPLETED',
  TRIP_CANCELLED: 'TRIP_CANCELLED',
  TRIP_DELAYED: 'TRIP_DELAYED',
  DRIVER_ON_DUTY: 'DRIVER_ON_DUTY',
  DRIVER_OFF_DUTY: 'DRIVER_OFF_DUTY',

  // Proximity & Boarding
  VEHICLE_APPROACHING: 'VEHICLE_APPROACHING',
  VEHICLE_ARRIVED: 'VEHICLE_ARRIVED',
  PICKUP_REMINDER: 'PICKUP_REMINDER',
  DROP_REMINDER: 'DROP_REMINDER',
  BOARDING_CONFIRMED: 'BOARDING_CONFIRMED',
  PASSENGER_NOT_BOARDED: 'PASSENGER_NOT_BOARDED',

  // Subscriptions & Payments
  SUBSCRIPTION_PURCHASED: 'SUBSCRIPTION_PURCHASED',
  SUBSCRIPTION_ACTIVATED: 'SUBSCRIPTION_ACTIVATED',
  SUBSCRIPTION_EXPIRING: 'SUBSCRIPTION_EXPIRING',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',

  // Daily Pass & QR
  DAILY_PASS_AVAILABLE: 'DAILY_PASS_AVAILABLE',
  QR_GENERATED: 'QR_GENERATED',
  QR_INVALID: 'QR_INVALID',
  QR_ALREADY_USED: 'QR_ALREADY_USED',

  // Route & Operational
  ROUTE_CHANGED: 'ROUTE_CHANGED',
  PICKUP_POINT_CHANGED: 'PICKUP_POINT_CHANGED',

  // Complaints & Support
  COMPLAINT_CREATED: 'COMPLAINT_CREATED',
  COMPLAINT_UPDATED: 'COMPLAINT_UPDATED',
  COMPLAINT_RESOLVED: 'COMPLAINT_RESOLVED',

  // Account & Verification
  ACCOUNT_CREATED: 'ACCOUNT_CREATED',
  ACCOUNT_UPDATED: 'ACCOUNT_UPDATED',
  ACCOUNT_VERIFIED: 'ACCOUNT_VERIFIED',
  ACCOUNT_REJECTED: 'ACCOUNT_REJECTED',
  KYC_SUBMITTED: 'KYC_SUBMITTED',

  // System & Admin Announcements
  SYSTEM_ANNOUNCEMENT: 'SYSTEM_ANNOUNCEMENT',
  IMPORTANT_ALERT: 'IMPORTANT_ALERT',
  MAINTENANCE: 'MAINTENANCE',
  ROUTE_UPDATE: 'ROUTE_UPDATE',
  SERVICE_UPDATE: 'SERVICE_UPDATE',
  EMERGENCY_SOS: 'EMERGENCY_SOS',

  // Legacy fallback types
  BOOKING: 'BOOKING',
  TRIP: 'TRIP',
  SUBSCRIPTION: 'SUBSCRIPTION',
  PAYMENT: 'PAYMENT',
  EMERGENCY: 'EMERGENCY',
  GENERAL: 'GENERAL',
} as const;
