export const USER_ROLES = {
  STUDENT: 'STUDENT',
  DRIVER: 'DRIVER',
  ADMIN: 'ADMIN',
} as const;

export const USER_STATUSES = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  DEACTIVATED: 'DEACTIVATED',
} as const;

export const VERIFICATION_STATUSES = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
} as const;

export const DRIVER_STATUSES = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
  ON_LEAVE: 'ON_LEAVE',
} as const;

export const VEHICLE_TYPES = {
  CAB_4: 'CAB_4',
  CAB_6: 'CAB_6',
  SHUTTLE_12: 'SHUTTLE_12',
  BUS_24: 'BUS_24',
} as const;

export const VEHICLE_STATUSES = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  MAINTENANCE: 'MAINTENANCE',
} as const;

export const PLAN_TIERS = {
  BASIC: 'BASIC',
  STANDARD: 'STANDARD',
  PREMIUM: 'PREMIUM',
} as const;

export const SUBSCRIPTION_STATUSES = {
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
} as const;

export const TRIP_TYPES = {
  MORNING_PICKUP: 'MORNING_PICKUP',
  EVENING_DROP: 'EVENING_DROP',
} as const;

export const TRIP_STATUSES = {
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export const BOOKING_STATUSES = {
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
  NO_SHOW: 'NO_SHOW',
} as const;

export const PASSENGER_STATUSES = {
  WAITING: 'WAITING',
  BOARDED: 'BOARDED',
  NO_SHOW: 'NO_SHOW',
} as const;

export const PASS_STATUSES = {
  ACTIVE: 'ACTIVE',
  USED: 'USED',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
} as const;

export const PAYMENT_METHODS = {
  UPI: 'UPI',
  DEBIT_CARD: 'DEBIT_CARD',
  CREDIT_CARD: 'CREDIT_CARD',
  NET_BANKING: 'NET_BANKING',
  WALLET: 'WALLET',
} as const;

export const PAYMENT_STATUSES = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
} as const;

export const COMPLAINT_CATEGORIES = {
  BOOKING: 'BOOKING',
  PAYMENT: 'PAYMENT',
  DRIVER: 'DRIVER',
  VEHICLE: 'VEHICLE',
  PASS_QR: 'PASS_QR',
  SUBSCRIPTION: 'SUBSCRIPTION',
  LOST_ITEM: 'LOST_ITEM',
  OTHER: 'OTHER',
} as const;

export const COMPLAINT_PRIORITIES = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
} as const;

export const COMPLAINT_STATUSES = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
} as const;

export const NOTIFICATION_TYPES = {
  BOOKING: 'BOOKING',
  TRIP: 'TRIP',
  SUBSCRIPTION: 'SUBSCRIPTION',
  PAYMENT: 'PAYMENT',
  EMERGENCY: 'EMERGENCY',
  GENERAL: 'GENERAL',
} as const;
